sudo: false
language: clojure
lein: 2.7.1
script:
  - ./scripts/test.sh $TEST
  - ./scripts/submit-to-coveralls.sh $TEST
env:
  matrix:
  - TEST=clj
  - TEST=cljs
jdk:
  - oraclejdk8
node_js:
  - "8.6"
cache:
  directories:
  - "$HOME/.m2"
